name: Release Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Updated to the latest stable version as of 2024

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          echo "Building binaries for all platforms"
          make build-all

      - name: Set execute permissions
        run: |
          chmod +x bin/namecheap-linux bin/namecheap-linux-arm bin/namecheap-macos

      - name: Generate checksums
        run: |
          cd bin
          sha256sum namecheap-linux namecheap-linux-arm namecheap-macos namecheap.exe > checksums.txt

      - name: Verify Binaries
        run: |
          ls -l bin/

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: bin/namecheap-linux

      - name: Upload Linux ARM Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-binary
          path: bin/namecheap-linux-arm

      - name: Upload MacOS Binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: bin/namecheap-macos

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: bin/namecheap.exe

      - name: Upload Checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: bin/checksums.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux Binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: bin

      - name: Download Linux ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: linux-arm-binary
          path: bin

      - name: Download MacOS Binary
        uses: actions/download-artifact@v4
        with:
          name: macos-binary
          path: bin

      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: bin

      - name: Download Checksums
        uses: actions/download-artifact@v4
        with:
          name: checksums
          path: bin

      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/namecheap-linux
          asset_name: namecheap-linux-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/namecheap-linux-arm
          asset_name: namecheap-linux-arm64-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload MacOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/namecheap-macos
          asset_name: namecheap-macos-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/namecheap.exe
          asset_name: namecheap-windows-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain