name: Release Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: Build
        run: make build

      - name: Verify Binary
        run: file bin/namecheap # Confirm the binary format

      - name: Archive Binary
        run: |
          cp bin/namecheap namecheap
          tar -cf namecheap.tar namecheap
          gzip namecheap.tar
          file namecheap.tar.gz # Check to confirm it’s gzipped

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: namecheap.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: release
          path: . # Download to the current directory

      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: namecheap.tar.gz
          asset_name: namecheap-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
